services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped

  db:
    image: postgres:15.13-alpine3.21
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"